In [1]:
from sklearn.decomposition import PCA
import numpy as np
from matplotlib import pyplot as plt

In [14]:
X = np.random.random((3,7))

In [25]:
p = PCA(n_components=3)
U, S, V = p._fit(X)
p.components_

array([[ 0.5443367 , -0.45774805,  0.4147663 ,  0.32714475, -0.45763969,
        -0.01020703,  0.07464073],
       [ 0.08735644, -0.51778431, -0.26075303, -0.01469188,  0.4420186 ,
        -0.59317653,  0.32988094],
       [-0.17347415,  0.52618253,  0.25855946,  0.53863672, -0.0389301 ,
        -0.4192957 ,  0.39841149]])

In [28]:
p = PCA(n_components=3)
p.fit(X)
p.components_

array([[ 0.5443367 , -0.45774805,  0.4147663 ,  0.32714475, -0.45763969,
        -0.01020703,  0.07464073],
       [ 0.08735644, -0.51778431, -0.26075303, -0.01469188,  0.4420186 ,
        -0.59317653,  0.32988094],
       [-0.17347415,  0.52618253,  0.25855946,  0.53863672, -0.0389301 ,
        -0.4192957 ,  0.39841149]])

In [29]:
p.transform(X)

array([[ -3.01212130e-02,   5.94222819e-01,   1.55400145e-17],
       [ -6.01599111e-01,  -3.18880359e-01,   4.77814969e-15],
       [  6.31720324e-01,  -2.75342460e-01,  -4.51483435e-15]])

In [30]:
p.components_

array([[ 0.5443367 , -0.45774805,  0.4147663 ,  0.32714475, -0.45763969,
        -0.01020703,  0.07464073],
       [ 0.08735644, -0.51778431, -0.26075303, -0.01469188,  0.4420186 ,
        -0.59317653,  0.32988094],
       [-0.17347415,  0.52618253,  0.25855946,  0.53863672, -0.0389301 ,
        -0.4192957 ,  0.39841149]])